# This document is a template with all the available configuration parameters

# Configuration for the station
[station]
name = "SRAM Station"
host = "127.0.0.1"
port = "5000"
secret_key = 'secret_key'
baudrate = { "USB0" = 350_000, "USB0" = 125_000 }
lower_bound = 6
higher_bound = 6

# Configuration for the databases
[databases]

[databases.mongo]
host = "localhost"
port = "27017"
name = "SRAM"

[databases.sqlite]
file = "/path/to/samples.db"

# Configuration for the loggers
[loggers]

[loggers.influx]
host = "127.0.0.1"
port = "8086"
name = "station"
